import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import Sidebar from "../app/sidebar"
import SignUp from "../app/sign-up/page"
import { useAuth } from "./context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { user, logOut } = useAuth();

  if (!user) {
    return <SignUp />;
  }

  
  return (
    <html lang="en">
      <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > <button onClick={logOut}>Sign out</button>
        <Sidebar/>
        {children}
       
      </body>
      </AuthProvider>
    </html>
  );
}
